### ISSUE TITLE
Separate Core DSI functionality from Driver and Plugin concepts

### ISSUE THREAD

**Issue by qwofford** [lanl/dsi#14]
I'm also interested in separating these concepts in a project structure like so:
```
<ROOT>/dsi
<ROOT>/dsi/core
<ROOT>/dsi/plugins
<ROOT>/dsi/drivers
 ...
```
Is that ok with you @jpulidojr ?

_Originally posted by @qwofford in https://github.com/lanl/dsi/issues/12#issuecomment-1581278928_

**Comment by qwofford** [comment]
PR addressing this should also address #16

**Comment by qwofford** [comment]
This work should move dsi/sql/* into a Driver implementation

**Comment by jpulidojr** [comment]
DSI should have abstract functions that work regardless of the plugin or driver. If I call "dsi.search("something"), it should work regardless of gufi, sql, or sqlalchemy, a relational, non-relational, graph database, etc.

As we tackle more usecases and apps, this functionality will expand.
----
I think it might be desirable to eventually create a simple internal test that combines all three, a plugin (a simple 'simulation' that generates 'dummy' ensemble data and metadata), interfaces with middleware (converts metadata to our internal representation), and an internal driver with no dependencies (sql). 

The wildfire dataset is a good first start, (wildfire -> csv -> sql) but the data is already generated and it is a simple 'csv' read and essentially skips the 'plugin' step. It serves as a "if you can output a csv, you can interface with DSI" purpose.

Bueno is a good first start as a plugin as it serves as a way to capture ensemble metadata, but we have the dependency of using Bueno, a 3rd party app.
