### ISSUE TITLE
Environment provenance plugin

### ISSUE THREAD

**Issue by qwofford** [lanl/dsi#17]
Create an plugin abstract class and implement an environment provenance capture implementation. The implementation should capture:
1. System Kernel version
2. Kernel compile-time config
3. Kernel boot config
4. Kernel runtime config
5. Kernel modules and module config
6. Container information, if containerized

**Comment by qwofford** [comment]
@DanielRJohnson Hold off on this until we discuss.

**Comment by DanielRJohnson** [comment]
This was merged in PR#18, further missing container provenance work will be in issue #48
