### ISSUE TITLE
Implement code coverage dashboard

### ISSUE THREAD

**Issue by qwofford** [lanl/dsi#20]
We should keep track of how rigorously our code is tested.

**Comment by DanielRJohnson** [comment]
This looks like it can be done with the `pytest-cov` pytest plugin:

https://pypi.org/project/pytest-cov/

It can output coverage to command-line with `pytest --cov` or can write out html with `pytest --cov --cov-report=html:<directory>`. In the future this could be integrated with CI to be made available for each commit/merge, possibly with the docs or somewhere else.

**Comment by qwofford** [comment]
Nice find.

I added a code coverage summary badge to our github project README, which is a link to the code coverage report.

This resolves when #18 is merged.
