### ISSUE TITLE
SQLAlchemy DSI backend integration

### ISSUE THREAD

**Issue by jpulidojr** [lanl/dsi#28]
Full SQLAlchemy backend integration after plugin/driver refactor is completed

**Comment by qwofford** [comment]
Should the SQLAlchemy piece be part of the middleware?

**Comment by jpulidojr** [comment]
SQLAlchemy can be middleware since it has its own abstract language to create databases, but we can also treat is as a driver because SQLAlchemy has access to multiple types of databases for non-relational data light graph databases.

In SQLAlchemy's dictionary, our "Drivers" are called "Dialects", and that toolkit gives you access to PostgreSQL, MySQL, SQLite, Oracle, and Microsoft SQL Server.

**Comment by cmahrens** [comment]
We asked this also and we discussed this at the Monday meeting. I think Quincy was pushing for it to be middleware.

**Comment by cmahrens** [comment]
Well, I mean "core" if that is what you are also meaning by middleware.

**Comment by qwofford** [comment]
Daniel is taking a look at Pydantic which might be helpful in conjunction with SQLAlchemy. See #51 and https://github.com/tiangolo/pydantic-sqlalchemy

**Comment by qwofford** [comment]
Optional Pydantic type checking is now in the main branch. If a Plugin implements type checking it can be static or dynamic. An example of static Plugin enforcement can be seen in the Hostname plugin. An example of the dynamic plugin can be seen in the Bueno model. It's still possible to create Plugins without Pydantic type enforcement if desired.

Daniel and I are working on to re-structure the code and documentation based on feedback we received from the group last week, and you can expect changes soon.
