### ISSUE TITLE
Make the Plugin abstract class commit-aware during pip installation

### ISSUE THREAD

**Issue by qwofford** [lanl/dsi#30]
We expect users to pip install DSI, and we have to support Plugin and Driver implementations which may be subject to versioning that is independent of the primary source code. However, there is only one git history representing the true DSI upstream repo. To manage this, I propose the following:

1. Expect that `pip` installs locally, or `pip` installs happen from a known packaging authority.
2. During a local pip install, we should grab then commit id from the git repository and hard-code this into the built modules.
3. When a DSI package is pushed to a pip package mirror, the commit id goes up with it.
4. When a DSI plugin or driver is used, the commit id is packaged with the DSI metadata buffer to be stored alongside other data artifacts.
5. When a users's metadata query is returned, the installed Plugin/Driver commits will also be returned.
6. If necessary, a Plugin/Driver should be able to interact with the git upstream hosted on Github to checkout a historical version of that Plugin or Driver.

**Comment by qwofford** [comment]
@DanielRJohnson Does this make sense, now that I've written it up?

**Comment by DanielRJohnson** [comment]
So is the main motivation that someone using a specific plugin/driver version to be able to checkout the DSI version that they were developed with (and are definitely compatible with)? If so, then coupling that with plugin metadata seems useful.

**Comment by qwofford** [comment]
Yes, particularly for the linkage between a producer Plugin and a consumer plugin. To make this concrete:

1. User asks `select * from blah where foo>2` 
2. DSI returns something like:
```
foo,plugin
2.2,{'file':'dsi.plugins.env', 'class':'Hostname', 'git_commit_sha':'abc123'}
2.1,{'file':'dsi.plugins.env', 'class':'Hostname', 'git_commit_sha':'abc123'}
2.5,{'file':'dsi.plugins.env', 'class':'Hostname', 'git_commit_sha':'abc123'}
9999,{'file':'dsi.plugins.env', 'class':'Hostname', 'git_commit_sha':'321cba'}
```

Depending on the application, the user might be suspicious that 9999 is much greater 2. If that result is suspicious, they will want to know how that data was produced. The plugin producer could then be inspected at that commit hash to see how the app was invoked to produce that result.

Further, a commit-aware Producer plugin can roll back to a previous version of the Plugin in order to reproduce results to see if the 9999 result is spurious or real.
